// flow-typed signature: c60c347af1a957976909856e321c653f
// flow-typed version: <<STUB>>/@hapi/joi_v^15.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hapi/joi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hapi/joi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hapi/joi/lib/cast' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/errors' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/language' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/ref' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/schemas' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/set' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/alternatives/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/any/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/any/settings' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/array/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/binary/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/boolean/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/date/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/func/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/lazy/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/number/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/object/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/state' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/string/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/string/ip' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/string/rfc3986' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/string/uri' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/symbol/index' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/symbols' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hapi/joi/lib/cast.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/cast'>;
}
declare module '@hapi/joi/lib/errors.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/errors'>;
}
declare module '@hapi/joi/lib/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/index'>;
}
declare module '@hapi/joi/lib/language.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/language'>;
}
declare module '@hapi/joi/lib/ref.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/ref'>;
}
declare module '@hapi/joi/lib/schemas.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/schemas'>;
}
declare module '@hapi/joi/lib/set.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/set'>;
}
declare module '@hapi/joi/lib/types/alternatives/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/alternatives/index'>;
}
declare module '@hapi/joi/lib/types/any/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/any/index'>;
}
declare module '@hapi/joi/lib/types/any/settings.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/any/settings'>;
}
declare module '@hapi/joi/lib/types/array/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/array/index'>;
}
declare module '@hapi/joi/lib/types/binary/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/binary/index'>;
}
declare module '@hapi/joi/lib/types/boolean/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/boolean/index'>;
}
declare module '@hapi/joi/lib/types/date/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/date/index'>;
}
declare module '@hapi/joi/lib/types/func/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/func/index'>;
}
declare module '@hapi/joi/lib/types/lazy/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/lazy/index'>;
}
declare module '@hapi/joi/lib/types/number/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/number/index'>;
}
declare module '@hapi/joi/lib/types/object/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/object/index'>;
}
declare module '@hapi/joi/lib/types/state.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/state'>;
}
declare module '@hapi/joi/lib/types/string/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/string/index'>;
}
declare module '@hapi/joi/lib/types/string/ip.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/string/ip'>;
}
declare module '@hapi/joi/lib/types/string/rfc3986.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/string/rfc3986'>;
}
declare module '@hapi/joi/lib/types/string/uri.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/string/uri'>;
}
declare module '@hapi/joi/lib/types/symbol/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/symbol/index'>;
}
declare module '@hapi/joi/lib/types/symbols.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/symbols'>;
}
