// flow-typed signature: f5f5d622f9e0be10e65cd7abdc7fd078
// flow-typed version: <<STUB>>/cosmiconfig_v^6.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cosmiconfig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cosmiconfig' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cosmiconfig/dist/cacheWrapper' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/Explorer' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/ExplorerBase' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/ExplorerSync' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/getDirectory' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/getPropertyByPath' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/loaders' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/readFile' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cosmiconfig/dist/cacheWrapper.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/cacheWrapper'>;
}
declare module 'cosmiconfig/dist/Explorer.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/Explorer'>;
}
declare module 'cosmiconfig/dist/ExplorerBase.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/ExplorerBase'>;
}
declare module 'cosmiconfig/dist/ExplorerSync.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/ExplorerSync'>;
}
declare module 'cosmiconfig/dist/getDirectory.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/getDirectory'>;
}
declare module 'cosmiconfig/dist/getPropertyByPath.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/getPropertyByPath'>;
}
declare module 'cosmiconfig/dist/index' {
  declare module.exports: $Exports<'cosmiconfig/dist'>;
}
declare module 'cosmiconfig/dist/index.js' {
  declare module.exports: $Exports<'cosmiconfig/dist'>;
}
declare module 'cosmiconfig/dist/loaders.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/loaders'>;
}
declare module 'cosmiconfig/dist/readFile.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/readFile'>;
}
declare module 'cosmiconfig/dist/types.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/types'>;
}
