// flow-typed signature: f5bf7c1a6d6078d6248eca8c9e479647
// flow-typed version: <<STUB>>/node-ssh_v^11.1.1/flow_v0.143.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-ssh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-ssh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-ssh/lib/cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-ssh/lib/cjs/index' {
  declare module.exports: $Exports<'node-ssh/lib/cjs'>;
}
declare module 'node-ssh/lib/cjs/index.js' {
  declare module.exports: $Exports<'node-ssh/lib/cjs'>;
}
