// flow-typed signature: 88e94483f2268a0f9478d1d968ce2627
// flow-typed version: <<STUB>>/node-ssh_v^7.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-ssh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-ssh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-ssh/lib/helpers' {
  declare module.exports: any;
}

declare module 'node-ssh/lib' {
  declare module.exports: any;
}

declare module 'node-ssh/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-ssh/lib/helpers.js' {
  declare module.exports: $Exports<'node-ssh/lib/helpers'>;
}
declare module 'node-ssh/lib/index' {
  declare module.exports: $Exports<'node-ssh/lib'>;
}
declare module 'node-ssh/lib/index.js' {
  declare module.exports: $Exports<'node-ssh/lib'>;
}
declare module 'node-ssh/lib/types.js' {
  declare module.exports: $Exports<'node-ssh/lib/types'>;
}
