// flow-typed signature: 8ee7cf50b7520a92944ffc879c160406
// flow-typed version: <<STUB>>/ssh2_v^0.8.4/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ssh2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ssh2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ssh2/examples/server-chat' {
  declare module.exports: any;
}

declare module 'ssh2/examples/sftp-server-download-only' {
  declare module.exports: any;
}

declare module 'ssh2/lib/agent' {
  declare module.exports: any;
}

declare module 'ssh2/lib/buffer-helpers' {
  declare module.exports: any;
}

declare module 'ssh2/lib/Channel' {
  declare module.exports: any;
}

declare module 'ssh2/lib/client' {
  declare module.exports: any;
}

declare module 'ssh2/lib/keepalivemgr' {
  declare module.exports: any;
}

declare module 'ssh2/lib/server' {
  declare module.exports: any;
}

declare module 'ssh2/lib/SFTPWrapper' {
  declare module.exports: any;
}

declare module 'ssh2/test/test-client-server' {
  declare module.exports: any;
}

declare module 'ssh2/test/test-openssh' {
  declare module.exports: any;
}

declare module 'ssh2/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ssh2/examples/server-chat.js' {
  declare module.exports: $Exports<'ssh2/examples/server-chat'>;
}
declare module 'ssh2/examples/sftp-server-download-only.js' {
  declare module.exports: $Exports<'ssh2/examples/sftp-server-download-only'>;
}
declare module 'ssh2/lib/agent.js' {
  declare module.exports: $Exports<'ssh2/lib/agent'>;
}
declare module 'ssh2/lib/buffer-helpers.js' {
  declare module.exports: $Exports<'ssh2/lib/buffer-helpers'>;
}
declare module 'ssh2/lib/Channel.js' {
  declare module.exports: $Exports<'ssh2/lib/Channel'>;
}
declare module 'ssh2/lib/client.js' {
  declare module.exports: $Exports<'ssh2/lib/client'>;
}
declare module 'ssh2/lib/keepalivemgr.js' {
  declare module.exports: $Exports<'ssh2/lib/keepalivemgr'>;
}
declare module 'ssh2/lib/server.js' {
  declare module.exports: $Exports<'ssh2/lib/server'>;
}
declare module 'ssh2/lib/SFTPWrapper.js' {
  declare module.exports: $Exports<'ssh2/lib/SFTPWrapper'>;
}
declare module 'ssh2/test/test-client-server.js' {
  declare module.exports: $Exports<'ssh2/test/test-client-server'>;
}
declare module 'ssh2/test/test-openssh.js' {
  declare module.exports: $Exports<'ssh2/test/test-openssh'>;
}
declare module 'ssh2/test/test.js' {
  declare module.exports: $Exports<'ssh2/test/test'>;
}
